img_path = '/l/users/shikhar.srivastava/data/pannuke/Fold 2/images/fold2/images.npy'
img = load_numpy_file(img_path)
type_path = '/l/users/shikhar.srivastava/data/pannuke/Fold 2/images/fold2/types.npy'
types = load_numpy_file(type_path)
mask_path = '/l/users/shikhar.srivastava/data/pannuke/Fold 2/masks/fold2/masks.npy'
masks = load_numpy_file(mask_path)


masks.shape

img.shape

types.shape

## Collate from multiple folds and write

import numpy as np
def collate_files(folds):
    img = np.empty((0, 256, 256, 3))
    type = np.empty((0))
    mask = np.empty((0, 256, 256, 6))
    for fold_id in range(1, folds+1):
        path = '/l/users/shikhar.srivastava/data/pannuke/Fold %d' % fold_id
        img_path = path + '/images/fold%d/images.npy' % fold_id
        type_path = path + '/images/fold%d/types.npy' % fold_id
        mask_path = path + '/masks/fold%d/masks.npy' % fold_id
        img_ = load_numpy_file(img_path)
        types_ = load_numpy_file(type_path)
        masks_ = load_numpy_file(mask_path)
        img = np.concatenate([img,img_], axis = 0)
        type = np.concatenate([type,types_], axis = 0)
        mask = np.concatenate([mask,masks_], axis = 0)
        print(fold_id, "\t", img.shape)
        print(fold_id, "\t", type.shape)
        del img_, types_, masks_
    return img, type, mask

img, type, mask = collate_files(3)

img.shape


write_dir = '/l/users/shikhar.srivastava/data/pannuke/full/'
write_numpy_file(write_dir + 'images.npy', img)
write_numpy_file(write_dir + 'types.npy', type)
write_numpy_file(write_dir + 'masks.npy', mask)

In [1]:
import numpy as np
# Load images from numpy array
def load_numpy_file(path):
    # Load numpy array
    arr = np.load(path)
    # Return a list of numpy arrays
    return arr
# Write numpy files to path
def write_numpy_file(path, arr):
    np.save(path, arr)
    return

### Pre-processing Masks to generate INST, TYPE MASKS

In [2]:
img_path = '/l/users/shikhar.srivastava/data/pannuke/full/images.npy'
img = load_numpy_file(img_path)
type_path = '/l/users/shikhar.srivastava/data/pannuke/full/types.npy'
types = load_numpy_file(type_path)
mask_path = '/l/users/shikhar.srivastava/data/pannuke/full/masks.npy'
masks = load_numpy_file(mask_path)

import numpy as np
from data_utils import *
# Exchange first and last dimensions so Background is dimension 0 and Neoplastic is dimension -1


In [3]:
ann_type, ann_inst = pre_processing_mask(masks)

Generating Instance, Type Masks: 100%|██████████| 7901/7901 [01:44<00:00, 75.86it/s] 


In [14]:
import pandas as pd

pd.DataFrame(ann_inst[:1000].flatten()).value_counts()

0      53536913
4        587724
5        582800
2        577964
3        572692
         ...   
116         235
117         148
120          85
118          80
119           2
Length: 121, dtype: int64

In [6]:
test = np.copy(masks)

In [7]:
binary_map = test[:,:,:,0]
inst_multichannel = test[:,:,:,1:]

In [10]:
import pandas as pd
pd.DataFrame(binarize(inst_multichannel[1]).flatten()).value_counts()

0     56815
10     2818
6      1062
3       925
9       868
7       832
8       813
5       549
1       421
2       327
4       106
dtype: int64

In [9]:
pd.DataFrame(masks[:,:,:,0].flatten()).value_counts()

1.0    420747521
0.0     97052415
dtype: int64

In [10]:
pd.DataFrame(masks[:,:,:,1].flatten()).value_counts()

0.0       508611437
12.0          28376
6.0           28210
8.0           28121
11.0          28039
            ...    
1457.0            6
2282.0            6
2293.0            4
2017.0            3
2082.0            2
Length: 2046, dtype: int64

In [11]:
pd.DataFrame(masks[:,:,:,2].flatten()).value_counts()

0.0       498450019
1.0          108851
2.0          107249
3.0           96515
8.0           94259
            ...    
2286.0           22
3506.0           20
2290.0           10
2291.0            6
1485.0            2
Length: 1931, dtype: int64

In [12]:
pd.DataFrame(masks[:,:,:,3].flatten()).value_counts()

0.0       517441913
1.0            2709
18.0           1843
136.0          1728
3.0            1538
            ...    
429.0             9
907.0             7
1366.0            6
763.0             2
3517.0            2
Length: 1934, dtype: int64

In [13]:
pd.DataFrame(masks[:,:,:,4].flatten()).value_counts()

0.0       504976797
30.0          40512
120.0         38871
144.0         37556
191.0         37155
            ...    
1345.0          111
914.0           111
1549.0          109
1127.0          106
1173.0           30
Length: 1138, dtype: int64

In [14]:
pd.DataFrame(masks[:,:,:,5].flatten()).value_counts()

0.0       472948872
1.0          180117
2.0          159209
6.0          158278
86.0         157542
            ...    
1850.0           14
2109.0           12
3515.0            8
2110.0            4
3514.0            3
Length: 2558, dtype: int64

In [6]:
import pandas as pd
check = pd.DataFrame(masks.flatten())

In [7]:
check.value_counts()

0.0       2599481453
1.0        421093062
2.0           326039
6.0           300073
3.0           297596
             ...    
3513.0            12
2325.0             9
3515.0             8
3514.0             3
3517.0             2
Length: 3463, dtype: int64

In [5]:
inst_mask = np.max(masks, axis = -1)

In [10]:
inst_mask

array([[[  1.,   1.,   1., ...,   1.,   1.,   1.],
        [  1.,   1.,   1., ...,   1.,   1.,   1.],
        [  1.,   1.,   1., ...,   1.,   1.,   1.],
        ...,
        [  1.,   1.,   1., ...,   1.,   1.,   1.],
        [  1.,   1.,   1., ...,   1.,   1.,   1.],
        [  1.,   1.,   1., ...,   1.,   1.,   1.]],

       [[  1.,   1.,   1., ...,   1.,   1.,   1.],
        [  1.,   1.,   1., ...,   1.,   1.,   1.],
        [  1.,   1.,   1., ...,   1.,   1.,   1.],
        ...,
        [  1.,   1.,   1., ...,   1.,   1.,   1.],
        [  1.,   1.,   1., ...,   1.,   1.,   1.],
        [  1.,   1.,   1., ...,   1.,   1.,   1.]],

       [[  1.,   1.,   1., ...,   1.,   1.,   1.],
        [  1.,   1.,   1., ...,   1.,   1.,   1.],
        [  1.,   1.,   1., ...,   1.,   1.,   1.],
        ...,
        [  1.,   1.,   1., ...,   1.,   1.,   1.],
        [  1.,   1.,   1., ...,   1.,   1.,   1.],
        [  1.,   1.,   1., ...,   1.,   1.,   1.]],

       ...,

       [[  1.,   1.,   1

In [7]:
_m = np.copy(masks)
_m[_m>=1] = 1
_m[_m<1] = 0
# Multiply each element of _m by its corresponding dimension index
_m = np.max(_m * np.arange(1, _m.shape[-1]+1), axis = -1) - 1
_m[_m<0] = 0

In [9]:
type_mask = np.copy(_m)

In [16]:
import os
write_dir = '/l/users/shikhar.srivastava/data/pannuke/proc4/'
if not os.path.exists(write_dir):
    os.makedirs(write_dir)
    
write_numpy_file(write_dir + 'inst_mask.npy', inst_mask)
write_numpy_file(write_dir + 'type_mask.npy', type_mask)

In [28]:
np.unique(inst_mask[:2000]).astype(int)

array([   0,    1,    2, ..., 3510, 3512, 4753])

In [29]:
np.unique(type_mask[:5000])

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [16]:
np.arange(1,5)

array([1, 2, 3, 4])

In [15]:
np.unique(type_mask[:2000])

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [58]:
np.unique(masks[0,:,:,1])

array([ 0., 19., 28.])

In [59]:
np.unique(masks[0,:,:,2])

array([ 0., 18., 41.])

In [60]:
np.unique(masks[0,:,:,3])

array([0.])

In [61]:
np.unique(masks[0,:,:,4])

array([0.])

In [62]:
np.unique(masks[0,:,:,5])

array([0., 1.])